config/routes.rb
Rails.application.routes.draw do
  get 'topics/new'
  get 'sessions/new'
  get 'users/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'pages#index'
  get 'pages/help'
  get 'pages/link'
  
  resources :users
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :topics
  
  get 'favorites/index'
  post '/favorites', to: 'favorites#create'
  delete '/favorites', to: 'favorites#destroy'
  
  resources :favorites
  
  resources :comments
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    validates :comment_content, presence: true
    
    belongs_to :user  #Comment.userでコメントの所有者を取得
    belongs_to :topic  #Comment.topicでそのコメントがされた投稿を取得
    
end

app/models/favorite.rb
class Favorite < ApplicationRecord
    
    belongs_to :user
    belongs_to :topic
end

app/models/topic.rb
class Topic < ApplicationRecord
    validates :user_id, presence: true
    validates :description, presence: true
    validates :image, presence: true
    
    belongs_to :user
    
    mount_uploader :image, ImageUploader
    
    has_many :favorites
    has_many :favorite_users, through: :favorites, source: 'user'
    has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true,
                   length: {maximum: 15, message: '名前は15文字まで'}
                   
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, 
                    format: {with: VALID_EMAIL_REGEX}
  
  VALID_PASSWORD_REGEX = /\A(?=.*?[a-z])(?=.*?[\d])[a-z\d]+\z/i.freeze          
  validates :password, presence: true, 
                       length: {in: 8..32, message: 'パスワードの文字数を8~32文字のみ可能'},
                       format: {with: VALID_PASSWORD_REGEX  ,message: '半角英数を両方含む必要があります'}
                       
  validates :password_confirmation, confirmation: true                     
  
  has_secure_password
  
  has_many :topics
  has_many :favorites
  has_many :favorite_topics, through: :favorites, source: 'topic'
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    protect_from_forgery with: :exception

    add_flash_types :success, :info, :warning, :danger
    
    #課題2の答え
    helper_method :current_user, :logged_in?
    
    def current_user
        @current_user = User.find_by(id: session[:user_id])
    end
    
    def logged_in?
        !current_user.nil?
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
    def new
      @comment = Comment.new
      @topic_id = params[:topic_id]
    end
    
    def create
      @comment = current_user.comments.new(comment_params)
      if @comment.save
        redirect_to topics_path, success: 'コメントしました'
      else
        flash.now[:danger] = "コメントできませんでした"
        render :new
      end
    end
    
    private
    def comment_params
        params.require(:comment).permit(:comment_content, :topic_id)
    end
    
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
    
    def index
      @favorite_topics = current_user.favorite_topics
    end

    def create
      favorite = Favorite.new
      favorite.user_id = current_user.id
      favorite.topic_id = params[:topic_id]

      if favorite.save
        redirect_to topics_path, success: 'お気に入りに登録しました'
      else
        redirect_to topics_path, danger: 'お気に入りに登録に失敗しました'
      end
      
    end
    
    def destroy
      favorite = Favorite.find_by(user_id: current_user.id, topic_id: params[:topic_id])
      favorite.destroy
      redirect_to topics_path, success: 'お気に入りを外しました'
    end
    
    
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
  
  def helpe
  end
  
  def link
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    #課題1の答え
    user = User.find_by(email: session_params[:email])
    if user && user.authenticate(session_params[:password])
      log_in user
      redirect_to root_path, success: 'ログインに成功しました'
    else
      flash.now[:danger] = 'ログインに失敗しました'
      render :new
    end
  end
  
  def destroy
    log_out
    redirect_to root_url, info: "ログアウトしました"
  end
  
  private 
  def log_in(user)
    session[:user_id] = user.id
  end
  
  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
  
  #課題1の答え
  private
  def session_params
    params.require(:session).permit(:email, :password)
  end
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  
  def index
    @topics = Topic.all.includes(:favorite_users)
  end
  
  def new
    @topic = Topic.new
  end

  def create
    @topic = current_user.topics.new(topic_params)

    if @topic.save
      redirect_to topics_path, success: '投稿に成功しました'
    else
      flash.now[:danger] = "投稿に失敗しました"
      render :new
    end
  end
  
  def show
    @topic = Topic.find(params:id)
  end

  private
  def topic_params
    params.require(:topic).permit(:image, :description)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, success: '登録が完了しました'
    else
      flash.now[:danger] = "登録に失敗しました"
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :password)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    
    
   
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Comment</h1>
         <%= form_for @comment do |f| %>
            <div class="form-group">
              <%= f.text_area :comment_content, class: 'form-control' %>
              <%= f.hidden_field :topic_id, :value => @topic_id %>
            </div>
            <%= f.submit 'コメントする', class: 'btn btn-black btn-block' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @favorite_topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <p class="topic-text">
              <%= topic.description %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pictgram</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    
  </head>

  <body>
    
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>" role="alert"><%= value %></div>
    <% end %>
    
    <nav class="navbar navbar-default navbar-fixed-top navbar-transparent">
      <div class="container">
        <%= link_to root_path do %>
          <span><%= image_tag "icons/logo.png", class: "navbar-brand" %></span>
        <% end %>
        <ul class="nav navbar-nav navbar-right">
          <% if logged_in? %>
            <li>
              <%= link_to favorites_index_path do %>
                <%= image_tag "icons/heart.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to new_topic_path do %>
                <%= image_tag "icons/camera.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to logout_path, method: :delete do %>
                <%= image_tag "icons/logout.png" %>
              <% end %>
            </li>
          <% else %>
            <li>
              <%= link_to new_user_path do %>
                <%= image_tag "icons/register.png" %>
              <% end %>
            </li>
            <li>
              <%= link_to login_path do %>
                <%= image_tag "icons/login.png" %>
              <% end %>
            </li>
          <% end %>
        </ul>
      </div>
    </nav>

    <%= yield %>
    
    <script>
      $(function(){
        $(".alert").fadeOut(5000);
      });
    </script>
    
  </body>
  
</html>

app/views/pages/help.html.erb
<h1>ヘルプページです</h1>

app/views/pages/index.html.erb
<div class="top-hero-wrapper text-center">
  <div class="container top-hero-container">
    <h1 class="text-white">Give People the Power to Build Community</h1>
    <h2 class="text-white">Pictgram is a service that you can post photos.</h2>
    <div class="row">
      <div class="col-md-offset-3 col-md-3">
        <%= link_to 'Sign up', new_user_path, class: 'btn btn-block btn-white' %>
      </div>
      <div class="col-md-3">
        <%= link_to 'Log in', login_path,class: 'btn btn-block btn-white' %>
      </div>
    </div>
  </div>
</div>

app/views/pages/link.html.erb
<h1>リンク集</h1>

app/views/topics/index.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    <% @topics.each do |topic| %>
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= topic.user.name %>
            </h2>
            <%= image_tag topic.image.url %>
            <% if !topic.favorite_users.include?(current_user) %>
              <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                <i class="fa fa-heart topic-index-icon unliked-btn"></i>
              <% end %>
            <% else %>
              <%= link_to favorites_path(topic_id: topic.id), method: :delete do %>
                <i class="fa fa-heart topic-index-icon liked-btn"></i>
              <% end %>
            <% end %>
            <%= topic.favorite_users.count %>
            <%= link_to new_comment_path(topic_id: topic.id) do %>
              <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <% end %>
            <p class="topic-text">
              <%= topic.description %>
            </p>
            
            <h4>コメント一覧</h4>
            <% topic.comments.each do |comment|%>
            <p class="topic-text">
              <%= comment.comment_content %>
            </p>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/topics/new.html.erb
<div class="topic-new-wrapper" >
  <div class="container">
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <h1 class="text-center">Add Picture</h1>
        <%= form_for @topic do |f| %>
          <div class="form-group">
            <%= f.label :image %>
            <%= f.file_field :image%>
          </div>

          <div class="form-group">
            <%= f.label :description %>
            <%= f.text_area :description, class: 'form-control' %>
          </div>
          <!-- 課題2の答え -->
          <% if current_user %>
              <%= f.submit '投稿', class: 'btn btn-black btn-block' %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/topics/show.html.erb
<div class="topic-index-wrapper">
  <div class="container">
    
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="topic-index-single">
            <h2 class="topic-author">
              <%= @topic.user.name %>
            </h2>
            <%= image_tag @topic.image.url %>
            <% if !@topic.favorite_users.include?(current_user) %>
              <%= link_to favorites_path(topic_id: topic.id), method: :post do %>
                <i class="fa fa-heart topic-index-icon unliked-btn"></i>
              <% end %>
            <% else %>
              <%= link_to favorites_path(topic_id: topic.id), method: :delete do %>
                <i class="fa fa-heart topic-index-icon liked-btn"></i>
              <% end %>
            <% end %>
            <%= @topic.favorite_users.count %>
            <%= image_tag 'icons/comment.png', class: 'topic-index-icon' %>
            <p class="topic-text">
              <%= @topic.description %>
            </p>
          </div>
        </div>
      </div>
    
    <h2>コメントする</h2>
    <%= form_with(model:[@post, @comment], method: :post) do |f| %>
        <%= f.text_area :comment_content %>
        <%= f.hidden_field :post_id, value: @post.id %>
        <%= f.submit 'コメントする' %>
    <% end %> 
    <h2>コメント一覧</h2>
    <%= @comments.each do |comment|%>
    <%= comment.comment_content %>  #コメントの内容が表示される
    <%= link_to 'ホーム', root_path %>
    
  </div>
</div>

app/views/users/new.html.erb
<div class="users-new-wrapper">
  <div class="container">
    <div class="row">
      <div class="col-md-offset-4 col-md-4 users-new-container">
        <h1 class="text-center text-white">Sign up</h1>
        <%= form_for @user do |f| %>
          <div class="form-group">
            <%= f.label :name, class: 'text-white' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :email, class: 'text-white' %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password, class: 'text-white' %>
            <%= f.password_field :password, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :password_confirmation, class: 'text-white' %>
            <%= f.password_field :password_confirmation, class: 'form-control' %>
          </div>

          <%= f.submit "登録", class: 'btn-block btn-white' %>
        <% end %>
        <%= link_to 'ログインはこちら', login_path, class: 'text-white' %>
      </div>
    </div>
  </div>
</div>